@startuml
start

:startPurchase;

:selectTicketType;

:selectTicketQuantity;

:choosePaymentMethod;

if (choosePaymentMethod) then (Cash)
  :processCashPayment;
  :paymentComplete;
elseif (choosePaymentMethod) then (Card)
  :processCardPayment;
  :paymentComplete;
else (Payment Failure)
  :handlePaymentFailure;
  if (handlePaymentFailure) then (Insufficient Funds)
    :handleInsufficientFunds;
    :purchaseComplete;
  elseif (handlePaymentFailure) then (Transaction Abort)
    :handleTransactionAbort;
    :purchaseComplete;
  endif
endif

:printTicket;

:sendTransactionConfirmation;

:purchaseComplete;

stop

@enduml