@startuml

class MetroStation {
  ID
  name
}

class TicketDistributor {
  ID
  type
  status
  capacity
}

class Traveller {
  ID
  age
  type
}

class Passenger {
  ID
  type
}

class Child {
  ID
  type
}

class Adult {
  ID
  type
}

class MetroPass {
  ID
  type
  duration
}

class TimeCard {
  ID
  type
  duration
}

class Transaction {
  ID
  status
  amount
}

class User {
  ID
  name
  registered_number
}

class Machine {
  ID
  type
  load_environment
}

class CurrencyNote {
  ID
  type
}

MetroStation --> TicketDistributor : uses
Traveller o-- Passenger : has
User --> Transaction : uses
Machine o-- DisplayInterface : has
PaymentMethod *-- Smartcard : owns
MetroPass o-- TimeCard : has
TicketDistributor --> User : uses
Traveller *-- Child : owns
Traveller *-- Adult : owns
MetroStation --> CurrencyNote : uses

@enduml