@startuml

class MetroStation {
  + ID
  + name
  + issueTicket()
  + issueMetroPass()
  + issueTimeCard()
}

class TicketDistributor {
  + ID
  + type
  + status
  + capacity
  + selectTripType()
  + selectQuantity()
  + choosePaymentMethod()
  + printTickets()
  + handleTransaction()
  + displayErrorMessage()
}

class Traveller {
  + ID
  + age
  + type
  + selectTripType()
  + selectQuantity()
  + issueMetroPass()
  + issueTimeCard()
}

class Passenger {
  + ID
  + type
  + issueMetroPass()
  + issueTimeCard()
}

class Child {
  + ID
  + type
  + issueTicket()
  + choosePaymentMethod()
}

class Adult {
  + ID
  + type
  + issueTicket()
  + choosePaymentMethod()
}

class MetroPass {
  + ID
  + type
  + duration
  + validateMetroPass()
  + displayErrorMessage()
}

class TimeCard {
  + ID
  + type
  + duration
  + validateTimeCard()
  + displayErrorMessage()
}

class Transaction {
  + ID
  + status
  + amount
  + payment_method
  + handleTransaction()
  + displayErrorMessage()
}

class User {
  + ID
  + name
  + registered_number
  + login()
  + logout()
  + displayErrorMessage()
}

class Machine {
  + ID
  + type
  + touch_screen
  + readMetroPass()
  + readTimeCard()
  + displayErrorMessage()
}

class TouchScreen {
  + ID
  + type
  + displayInterface()
  + handleInput()
  + displayErrorMessage()
}

class CurrencyNote {
  + ID
  + type
  + validateCurrencyNote()
  + displayErrorMessage()
}

MetroStation "1" o-- "1" TicketDistributor : Has
MetroStation "*" --> "*" Traveller : Has
TicketDistributor "1" o-- "1" Passenger : Issues
TicketDistributor "*" --> "*" Child : Is a type of
TicketDistributor "*" --> "*" Adult : Is a type of
TicketDistributor "1" o-- "1" MetroPass : Issues
TicketDistributor "1" o-- "1" TimeCard : Issues
Transaction "*" --> "*" PaymentMethod : Uses
TicketDistributor "1" *-- "1" DisplayInterface : Uses
TicketDistributor "1" *-- "1" TouchScreen : Uses
Transaction "*" --> "*" User : Issued to
TicketDistributor "1" o-- "1" Machine : Uses
Transaction "*" --> "*" CurrencyNote : Uses
TicketDistributor "1" *-- "1" Error : Handles
Transaction "1" *-- "1" ErrorMessage : Displays

@enduml