@startuml
start

while (More cars arriving?) is (yes)
    :Insert Identity Card;
    if (Is it an employee card?) then (yes)
        :Verify Card Number;
        if (Is Card Valid?) then (yes)
            :Check Parking Spaces;
            if (Parking Space Available?) then (yes)
                fork
                    :Raise Barrier;
                fork again
                    :Car enters car park;
                end fork
            else (no)
                :Display "Full" sign;
                :Reject Card;
            endif
        else (no)
            :Reject Card;
        endif
    else (no)
        :Verify Guest Card;
        if (Is Guest Card Valid?) then (yes)
            :Check Parking Spaces;
            if (Parking Space Available?) then (yes)
                fork
                    :Raise Barrier;
                fork again
                    :Car enters car park;
                end fork
            else (no)
                :Display "Full" sign;
                :Reject Guest Card;
            endif
        else (no)
            :Reject Guest Card;
        endif
    endif
endwhile

while (More cars leaving?) is (yes)
    :Car leaves car park;
    :Raise Exit Barrier;
    :Check Parking Spaces;
    if (Parking Space Available?) then (yes)
        :Switch off "Full" sign;
    endif
endwhile

stop
@enduml