@startuml
start

:collectGuestCard;
:insertIdentityCard;
:verifyCardNumber;

if (isCardNumberValid?) then (true)
    :issueIdentityCard;
    :raiseBarrier;
    :displayFullSign;
else (false)
    :returnGuestCard;
endif

:mergeAfterValidation;
:lowerBarrier;
:switchOffFullSign;

stop
@enduml