@startuml
start

:insertIdentityCard;
:verifyCardNumber;
if (isIdentityValid?) then (true)
    :issueIdentityCard;
else (false)
    :collectGuestCard;
endif
:mergePostIdentityCheck;
:raiseBarrier;
:displayFullSign;
:lowerBarrier;
:switchOffFullSign;

stop
@enduml