@startuml
start

while (More cars arriving?) is (yes)
    :Insert Identity Card;
    :Verify Card;
    if (Card Valid?) then (yes)
        :Check Parking Spaces;
        if (Parking Space Available?) then (yes)
            fork
                :Raise Barrier;
            fork again
                :Car enters car park;
            end fork
        else (no)
            :Display "Full" sign;
            :Return Card;
        endif
    else (no)
        :Return Card;
    endif
endwhile

' while (More cars leaving?) is (yes)
'     :Car leaves car park;
'     :Raise Exit Barrier;
'     :Check Parking Spaces;
'     if (Parking Space Available?) then (yes)
'         :Switch off "Full" sign;
'     endif
'     if (Is Guest Card?) then (yes)
'         :Return Guest Card to Reception;
'     endif
' endwhile

stop
@enduml